### ISSUE TITLE
setTabFont example in /usr/share/doc/termit/rc.lua.example fails

### ISSUE THREAD

**Issue by bhepple** [nonstop/termit#104]
this one works for me with 'Monospace 8':

    setTabFont(string.sub(tab.font, 1, string.find(tab.font, '[0-9.]+$') - 1)..(tab.fontSize + delta))

termit-2.9.6-8.fc24.x86_64

**Comment by nonstop** [comment]
I am using termit-3 and lua 5.2
example with Increase/Decrease font works fine

Your only change is replacing '%d' with '[0-9.]+'.
Though Lua docs tell us
> %d: represents all digits.
The only change is adding 'dot' to this list.
Do you have fonts with float size?

**Comment by bhepple** [comment]
Yes - tab.fontSize is a float:

Adding some debug:

    function changeTabFontSize(delta)
        tab = tabs[currentTabIndex()]
        print (tab.font)
        print (tab.fontSize)
        print (tab.fontSize + delta)
        setTabFont(string.sub(tab.font, 1, string.find(tab.font, '[0-9.]+$') - 1)..(tab.fontSize + delta))
    end

... results in:

Monospace 8
8.0
9.0

**Comment by nonstop** [comment]
look, there are not dots in 'Monospace 8' string
try to compile termit with lua-5.2
may be it it lua issue

**Comment by bhepple** [comment]
> there are not dots in 'Monospace 8' string

No, but in tab.fontSize it is returned as '8.0'

The new pattern works in the existing fedora build and would work in builds where it is returned as a plain '8' so why not just merge it in?

**Comment by nonstop** [comment]
I've checked termit with lua-5.3.
It prints any number with '.0' at the end. It even print tab.pid with .0 at the end.
I'll try to investigate this further.
Right now I do not see any reasons to change rc.lua in docs.

**Comment by tdussa** [comment]
The sample rc.lua font size magic doesn't work for me either.  It appears that some locale problem breaks this on my machine; the font size is somehow represented with a comma instead of a period (as in "15,0" instead of "15.0").  This apparently makes setTabFont() puke.  See my pull request for a fix/workaround for this.

On a side note, yes, there are fractional font sizes.  "%d" is insufficient, this needs to be "[%d.]".  You can jolly well specify your font size to be 15.5, so this should be handled properly.

**Comment by nonstop** [comment]
attach an output for `locale`

**Comment by bhepple** [comment]
LANG=C
    LC_CTYPE="en_AU.utf8"
    LC_NUMERIC="en_AU.utf8"
    LC_TIME="en_AU.utf8"
    LC_COLLATE="en_AU.utf8"
    LC_MONETARY="en_AU.utf8"
    LC_MESSAGES="en_AU.utf8"
    LC_PAPER="en_AU.utf8"
    LC_NAME="en_AU.utf8"
    LC_ADDRESS="en_AU.utf8"
    LC_TELEPHONE="en_AU.utf8"
    LC_MEASUREMENT="en_AU.utf8"
    LC_IDENTIFICATION="en_AU.utf8"
    LC_ALL=en_AU.utf8

**Comment by tdussa** [comment]
Find my locale output attached.

I don't see how this helps with the problem at hand though.  This issue is about making the sample code more robust, there is an easy fix for the issue at hand, and it doesn't break anything.  Why not just merge it and improve the robustness of the example?

---
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_ALL=
---

**Comment by nonstop** [comment]
1eea176
